basePath: /v2
definitions:
  analyze.Request:
    properties:
      address:
        type: string
    required:
    - address
    type: object
  analyze.Response:
    properties:
      message:
        type: string
      status:
        type: string
      transactions:
        items:
          $ref: '#/definitions/moralis.Transaction'
        type: array
    type: object
  checkalive.Response:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        type: string
    type: object
  error.BadRequestErr:
    properties:
      error:
        example: bad request
        type: string
    type: object
  error.InternalErr:
    properties:
      error:
        example: internal error
        type: string
    type: object
  moralis.Transaction:
    properties:
      blockNumber:
        type: integer
      blockTimestamp:
        type: string
      from:
        type: string
      hash:
        type: string
      to:
        type: string
      value:
        type: string
    type: object
  response.Response:
    properties:
      code:
        example: 200
        type: integer
      message:
        example: OK
        type: string
    type: object
host: petstore.swagger.io
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /api/v1/alive:
    get:
      consumes:
      - application/json
      description: Проверка доступен ли сервис
      produces:
      - application/json
      responses:
        "200":
          description: Service alive
          schema:
            $ref: '#/definitions/checkalive.Response'
        "400":
          description: Invalid input
          schema:
            $ref: '#/definitions/response.Response'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.Response'
      summary: Проверка доступен ли сервис
  /api/v1/analyze:
    post:
      consumes:
      - application/json
      description: Get transactions for Ethereum address using Moralis API
      parameters:
      - description: Ethereum address to analyze
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/analyze.Request'
      produces:
      - application/json
      responses:
        "200":
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/analyze.Response'
        "400":
          description: Invalid Ethereum address
          schema:
            $ref: '#/definitions/error.BadRequestErr'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/error.InternalErr'
      summary: Analyze Ethereum address
      tags:
      - analyze
swagger: "2.0"
